create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
create sequence ejercicio_en_rutina_seq start with 1 increment by 50;
create sequence ejercicio_seq start with 1 increment by 50;
create sequence rutina_seq start with 1 increment by 50;
create table ejercicio (entrenador integer, id bigint not null, descripcion varchar(255), dificultad varchar(255), material varchar(255), musculos_trabajados varchar(255), nombre varchar(255), observaciones varchar(255), tipo varchar(255), primary key (id));
create table ejercicio_en_rutina (duracion_minutos integer not null, repeticiones integer not null, series integer not null, ejercicio_id bigint, id bigint not null, primary key (id));
create table multimedia (ejercicio_id bigint not null, url varchar(255));
create table rutina (entrenador integer, id bigint not null, descripcion varchar(255), nombre varchar(255), observaciones varchar(255), primary key (id));
create table rutina_ejercicios (ejercicios_id bigint not null unique, rutina_id bigint not null);
alter table if exists ejercicio_en_rutina add constraint FKcna71mi3idacv0tqsuado2rsf foreign key (ejercicio_id) references ejercicio;
alter table if exists multimedia add constraint FKokc6ykxo36mlprpivvetueg9f foreign key (ejercicio_id) references ejercicio;
alter table if exists rutina_ejercicios add constraint FK8msj88c4iy8s03u3kvxshp51i foreign key (ejercicios_id) references ejercicio_en_rutina;
alter table if exists rutina_ejercicios add constraint FKmcb9eic73952ml9qd0113uq1n foreign key (rutina_id) references rutina;
